#!/bin/bash -l 


#!/bin/bash
#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH --account=m77
#SBATCH -J CQL3D
##SBATCH --mail-user=petrov@compxco.com
##SBATCH --mail-type=ALL
#SBATCH -t 01:20:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

cd $SLURM_SUBMIT_DIR

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/global/cfs/cdirs/m77/CompX/pgplot/pgplot.perl.gnu

#run the application (Perlmutter has 128x2 cpucores per node)
srun -n 128 -c 2 --cpu_bind=cores ./xcql3d_mpi_gnu.perl
